# Generated by Django 5.2.3 on 2025-08-04 03:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=60)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Solo se permiten números, espacios, y los símbolos + - ( )', regex='^\\+?[\\d\\s\\-\\(\\)]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=60)),
                ('rol', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='estado_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Bueno', 'Bueno'), ('Dañado', 'Dañado')], default='Bueno', max_length=10)),
                ('descripcion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='metodo_de_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_pago', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='montoenvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Nacional', 'Nacional'), ('Latinoamérica', 'Latinoamérica'), ('Internacional', 'Internacional')], max_length=20)),
                ('costo_por_libra', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_producto', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.CharField(max_length=100)),
                ('Descripcion_product', models.CharField(blank=True, max_length=300)),
                ('peso', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='rol_administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='rol_empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=300)),
                ('telefono', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Solo se permiten números, espacios, y los símbolos + - ( )', regex='^\\+?[\\d\\s\\-\\(\\)]+$')])),
            ],
        ),
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('monto_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carritos', to='api.montoenvio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to='api.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilidad', models.CharField(choices=[('Disponible', 'Disponible'), ('Agotado', 'Agotado')], default='Disponible', max_length=10)),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidad_producto', to='api.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productos')),
            ],
        ),
        migrations.CreateModel(
            name='carritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api.productos')),
            ],
        ),
        migrations.CreateModel(
            name='productos_x_ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_x_ventas', to='api.productos')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedoresXProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_producto', to='api.productos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_proveedor', to='api.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='productos',
            name='proveedores',
            field=models.ManyToManyField(related_name='productos', through='api.ProveedoresXProducto', to='api.proveedor'),
        ),
        migrations.CreateModel(
            name='rol_x_administradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_administradores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_x_administradores', to='api.rol_administradores')),
                ('id_rol_administradores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_x_administradores', to='api.admins')),
            ],
        ),
        migrations.CreateModel(
            name='rol_x_empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_x_empleado', to='api.empleados')),
                ('id_Rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol_x_empleado', to='api.rol_empleados')),
            ],
        ),
        migrations.CreateModel(
            name='stock_productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_disponibilidad', to='api.disponibilidad')),
                ('id_estado_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_estado', to='api.estado_producto')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_productos', to='api.productos')),
            ],
        ),
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_empleados', to='api.empleados')),
                ('metodo_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_metodo_pago', to='api.metodo_de_pago')),
                ('productos', models.ManyToManyField(related_name='ventas_productos', through='api.productos_x_ventas', to='api.productos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_usuario', to='api.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='productos_x_ventas',
            name='id_ventas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_x_ventas', to='api.ventas'),
        ),
    ]
